/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.meetup.sink.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CustomerFinal extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6620726117836246949L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerFinal\",\"namespace\":\"com.meetup.sink.schema\",\"fields\":[{\"name\":\"FIRST_NAME\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"LAST_NAME\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"EMAIL\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CustomerFinal> ENCODER =
      new BinaryMessageEncoder<CustomerFinal>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CustomerFinal> DECODER =
      new BinaryMessageDecoder<CustomerFinal>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CustomerFinal> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CustomerFinal> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CustomerFinal> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CustomerFinal>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CustomerFinal to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CustomerFinal from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CustomerFinal instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CustomerFinal fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence FIRST_NAME;
   private java.lang.CharSequence LAST_NAME;
   private java.lang.CharSequence EMAIL;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CustomerFinal() {}

  /**
   * All-args constructor.
   * @param FIRST_NAME The new value for FIRST_NAME
   * @param LAST_NAME The new value for LAST_NAME
   * @param EMAIL The new value for EMAIL
   */
  public CustomerFinal(java.lang.CharSequence FIRST_NAME, java.lang.CharSequence LAST_NAME, java.lang.CharSequence EMAIL) {
    this.FIRST_NAME = FIRST_NAME;
    this.LAST_NAME = LAST_NAME;
    this.EMAIL = EMAIL;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return FIRST_NAME;
    case 1: return LAST_NAME;
    case 2: return EMAIL;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: FIRST_NAME = (java.lang.CharSequence)value$; break;
    case 1: LAST_NAME = (java.lang.CharSequence)value$; break;
    case 2: EMAIL = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'FIRST_NAME' field.
   * @return The value of the 'FIRST_NAME' field.
   */
  public java.lang.CharSequence getFIRSTNAME() {
    return FIRST_NAME;
  }


  /**
   * Sets the value of the 'FIRST_NAME' field.
   * @param value the value to set.
   */
  public void setFIRSTNAME(java.lang.CharSequence value) {
    this.FIRST_NAME = value;
  }

  /**
   * Gets the value of the 'LAST_NAME' field.
   * @return The value of the 'LAST_NAME' field.
   */
  public java.lang.CharSequence getLASTNAME() {
    return LAST_NAME;
  }


  /**
   * Sets the value of the 'LAST_NAME' field.
   * @param value the value to set.
   */
  public void setLASTNAME(java.lang.CharSequence value) {
    this.LAST_NAME = value;
  }

  /**
   * Gets the value of the 'EMAIL' field.
   * @return The value of the 'EMAIL' field.
   */
  public java.lang.CharSequence getEMAIL() {
    return EMAIL;
  }


  /**
   * Sets the value of the 'EMAIL' field.
   * @param value the value to set.
   */
  public void setEMAIL(java.lang.CharSequence value) {
    this.EMAIL = value;
  }

  /**
   * Creates a new CustomerFinal RecordBuilder.
   * @return A new CustomerFinal RecordBuilder
   */
  public static com.meetup.sink.schema.CustomerFinal.Builder newBuilder() {
    return new com.meetup.sink.schema.CustomerFinal.Builder();
  }

  /**
   * Creates a new CustomerFinal RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerFinal RecordBuilder
   */
  public static com.meetup.sink.schema.CustomerFinal.Builder newBuilder(com.meetup.sink.schema.CustomerFinal.Builder other) {
    if (other == null) {
      return new com.meetup.sink.schema.CustomerFinal.Builder();
    } else {
      return new com.meetup.sink.schema.CustomerFinal.Builder(other);
    }
  }

  /**
   * Creates a new CustomerFinal RecordBuilder by copying an existing CustomerFinal instance.
   * @param other The existing instance to copy.
   * @return A new CustomerFinal RecordBuilder
   */
  public static com.meetup.sink.schema.CustomerFinal.Builder newBuilder(com.meetup.sink.schema.CustomerFinal other) {
    if (other == null) {
      return new com.meetup.sink.schema.CustomerFinal.Builder();
    } else {
      return new com.meetup.sink.schema.CustomerFinal.Builder(other);
    }
  }

  /**
   * RecordBuilder for CustomerFinal instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerFinal>
    implements org.apache.avro.data.RecordBuilder<CustomerFinal> {

    private java.lang.CharSequence FIRST_NAME;
    private java.lang.CharSequence LAST_NAME;
    private java.lang.CharSequence EMAIL;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.meetup.sink.schema.CustomerFinal.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.FIRST_NAME)) {
        this.FIRST_NAME = data().deepCopy(fields()[0].schema(), other.FIRST_NAME);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.LAST_NAME)) {
        this.LAST_NAME = data().deepCopy(fields()[1].schema(), other.LAST_NAME);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.EMAIL)) {
        this.EMAIL = data().deepCopy(fields()[2].schema(), other.EMAIL);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CustomerFinal instance
     * @param other The existing instance to copy.
     */
    private Builder(com.meetup.sink.schema.CustomerFinal other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.FIRST_NAME)) {
        this.FIRST_NAME = data().deepCopy(fields()[0].schema(), other.FIRST_NAME);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.LAST_NAME)) {
        this.LAST_NAME = data().deepCopy(fields()[1].schema(), other.LAST_NAME);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.EMAIL)) {
        this.EMAIL = data().deepCopy(fields()[2].schema(), other.EMAIL);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'FIRST_NAME' field.
      * @return The value.
      */
    public java.lang.CharSequence getFIRSTNAME() {
      return FIRST_NAME;
    }


    /**
      * Sets the value of the 'FIRST_NAME' field.
      * @param value The value of 'FIRST_NAME'.
      * @return This builder.
      */
    public com.meetup.sink.schema.CustomerFinal.Builder setFIRSTNAME(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.FIRST_NAME = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'FIRST_NAME' field has been set.
      * @return True if the 'FIRST_NAME' field has been set, false otherwise.
      */
    public boolean hasFIRSTNAME() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'FIRST_NAME' field.
      * @return This builder.
      */
    public com.meetup.sink.schema.CustomerFinal.Builder clearFIRSTNAME() {
      FIRST_NAME = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'LAST_NAME' field.
      * @return The value.
      */
    public java.lang.CharSequence getLASTNAME() {
      return LAST_NAME;
    }


    /**
      * Sets the value of the 'LAST_NAME' field.
      * @param value The value of 'LAST_NAME'.
      * @return This builder.
      */
    public com.meetup.sink.schema.CustomerFinal.Builder setLASTNAME(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.LAST_NAME = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'LAST_NAME' field has been set.
      * @return True if the 'LAST_NAME' field has been set, false otherwise.
      */
    public boolean hasLASTNAME() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'LAST_NAME' field.
      * @return This builder.
      */
    public com.meetup.sink.schema.CustomerFinal.Builder clearLASTNAME() {
      LAST_NAME = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'EMAIL' field.
      * @return The value.
      */
    public java.lang.CharSequence getEMAIL() {
      return EMAIL;
    }


    /**
      * Sets the value of the 'EMAIL' field.
      * @param value The value of 'EMAIL'.
      * @return This builder.
      */
    public com.meetup.sink.schema.CustomerFinal.Builder setEMAIL(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.EMAIL = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'EMAIL' field has been set.
      * @return True if the 'EMAIL' field has been set, false otherwise.
      */
    public boolean hasEMAIL() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'EMAIL' field.
      * @return This builder.
      */
    public com.meetup.sink.schema.CustomerFinal.Builder clearEMAIL() {
      EMAIL = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CustomerFinal build() {
      try {
        CustomerFinal record = new CustomerFinal();
        record.FIRST_NAME = fieldSetFlags()[0] ? this.FIRST_NAME : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.LAST_NAME = fieldSetFlags()[1] ? this.LAST_NAME : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.EMAIL = fieldSetFlags()[2] ? this.EMAIL : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CustomerFinal>
    WRITER$ = (org.apache.avro.io.DatumWriter<CustomerFinal>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CustomerFinal>
    READER$ = (org.apache.avro.io.DatumReader<CustomerFinal>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.FIRST_NAME == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.FIRST_NAME);
    }

    if (this.LAST_NAME == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.LAST_NAME);
    }

    if (this.EMAIL == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.EMAIL);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.FIRST_NAME = null;
      } else {
        this.FIRST_NAME = in.readString(this.FIRST_NAME instanceof Utf8 ? (Utf8)this.FIRST_NAME : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.LAST_NAME = null;
      } else {
        this.LAST_NAME = in.readString(this.LAST_NAME instanceof Utf8 ? (Utf8)this.LAST_NAME : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.EMAIL = null;
      } else {
        this.EMAIL = in.readString(this.EMAIL instanceof Utf8 ? (Utf8)this.EMAIL : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.FIRST_NAME = null;
          } else {
            this.FIRST_NAME = in.readString(this.FIRST_NAME instanceof Utf8 ? (Utf8)this.FIRST_NAME : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.LAST_NAME = null;
          } else {
            this.LAST_NAME = in.readString(this.LAST_NAME instanceof Utf8 ? (Utf8)this.LAST_NAME : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.EMAIL = null;
          } else {
            this.EMAIL = in.readString(this.EMAIL instanceof Utf8 ? (Utf8)this.EMAIL : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










