spring:
  cloud:
    stream:
      function:
        definition: customerTableSink,addressTableSink
      bindings:
        customerTableSink-in-0:
          destination: customers.sink.final.customer
        addressTableSink-in-0:
          destination: customers.sink.address.table.final


      kafka:
        consumer:
          auto-offset-reset: earliest
        bindings:
        streams:
          binder:
            functions:
              customerTableSink.applicationId: testCustGrp5
              addressTableSink.applicationId: testAddrGrp5
            configuration:
              schema.registry.url: http://localhost:8081
              specific.avro.reader: true
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  kafka:
    bootstrapServers: localhost:29092

  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: mysqluser
    password: mysqlpw

customer:
  target:
    id:
      topic: customers.sink.target.id
